name: linting, testing, building
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.nove-version }}
       uses: actions/setuop-node@v1
       width:
         node-version: ${{ matrix.node-version }}   
      - name: install modules
        run: npm install
      - name: build producton project
        run: npm run build:prod
      - name: linting typesript
        run: npm run lint:ts 
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: linting css
        run: npm run lint:scss